import Head from 'next/head'
import { Inter } from '@next/font/google'
import Header from '../layouts/header/head'
import  Sec from  '../components/sections/MainSection'
import Sec1 from '../components/sections/TrakingApplication'
import Sec2 from "../components/sections/Achievements"
import Sec5 from "../components/sections/ClintsSays"
import OurVision from '../components/sections/OurVision'
import VSection from '@/components/sections/VideoSection'
import SwideSilper from '@/components/sections/SwideSilper'
import Footer from '@/layouts/footer/Footer'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Header />
    <Sec />
    <Sec1 />
    <Sec2 />
    <Sec5 />
    <OurVision />
     <VSection /> 
     <SwideSilper />
     <Footer />
    
    </> 
  )
}
